# SPDX-FileCopyrightText: 2026 4ntenna <4ntenn@proton.me>, The Hokora Project
# SPDX-License-Identifier: AGPL-3.0-only
"""Async SQLAlchemy engine factory with WAL mode and optional SQLCipher."""

import logging
import re
from pathlib import Path
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import event

logger = logging.getLogger(__name__)

_sqlcipher_patched = False


def _patch_aiosqlite_for_sqlcipher():
    """Make aiosqlite use sqlcipher3 instead of stdlib sqlite3."""
    global _sqlcipher_patched
    if _sqlcipher_patched:
        return True
    try:
        import sqlcipher3
        import aiosqlite.core as aiosqlite_core

        aiosqlite_core.sqlite3 = sqlcipher3
        _sqlcipher_patched = True
        return True
    except ImportError:
        return False


def create_db_engine(
    db_path: Path,
    encrypt: bool = False,
    db_key: Optional[str] = None,
    echo: bool = False,
) -> AsyncEngine:
    """Create an async SQLAlchemy engine with appropriate pragmas."""
    if encrypt and db_key:
        if not re.match(r"^[0-9a-fA-F]+$", db_key) or len(db_key) != 64:
            raise ValueError(
                "db_key must be exactly 64 hex characters (generated by 'hokora init')"
            )
        if _patch_aiosqlite_for_sqlcipher():
            logger.info("Using SQLCipher for encrypted database")
        else:
            raise RuntimeError(
                "SQLCipher is required but sqlcipher3 is not installed. "
                "Install with: pip install sqlcipher3"
            )

    url = f"sqlite+aiosqlite:///{db_path}"
    engine = create_async_engine(url, echo=echo, pool_pre_ping=True)

    @event.listens_for(engine.sync_engine, "connect")
    def set_sqlite_pragma(dbapi_conn, connection_record):
        cursor = dbapi_conn.cursor()
        if encrypt and db_key:
            # SECURITY: re-validate at point of use (defense-in-depth); PRAGMA key
            # does not support ? binding, so we use SQLCipher hex key literal x'...'
            # which only accepts [0-9a-fA-F] — structurally immune to injection.
            assert re.match(r"^[0-9a-fA-F]{64}$", db_key), "db_key must be 64 hex chars"
            cursor.execute("PRAGMA key=\"x'" + db_key + "'\"")
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.execute("PRAGMA synchronous=NORMAL")
        cursor.execute("PRAGMA busy_timeout=5000")
        cursor.close()

    return engine


def create_session_factory(engine: AsyncEngine) -> sessionmaker:
    """Create an async session factory."""
    return sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def init_db(engine: AsyncEngine):
    """Create all tables."""
    from hokora.db.models import Base

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def check_alembic_revision(engine: AsyncEngine):
    """Verify the database is at the expected Alembic head revision.

    - Fresh DB (no alembic_version table): stamps to head via INSERT.
    - DB at head: passes silently.
    - DB at old revision: raises RuntimeError.
    - Missing alembic dir: logs warning and skips.
    """

    # Find alembic/ directory by walking up from this file
    alembic_dir = None
    search = Path(__file__).resolve().parent
    for _ in range(10):
        candidate = search / "alembic"
        if candidate.is_dir() and (candidate / "env.py").exists():
            alembic_dir = candidate
            break
        search = search.parent

    if alembic_dir is None:
        logger.warning(
            "Alembic directory not found — skipping migration check. "
            "Run 'hokora db upgrade' manually if needed."
        )
        return

    try:
        from alembic.config import Config as AlembicConfig
        from alembic.script import ScriptDirectory
    except ImportError:
        logger.warning("Alembic not installed — skipping migration check")
        return

    alembic_ini = alembic_dir.parent / "alembic.ini"
    alembic_cfg = AlembicConfig(str(alembic_ini) if alembic_ini.exists() else None)
    alembic_cfg.set_main_option("script_location", str(alembic_dir))

    script = ScriptDirectory.from_config(alembic_cfg)
    head_rev = script.get_current_head()

    if head_rev is None:
        logger.warning("No Alembic revisions found — skipping migration check")
        return

    def _check_revision(connection):
        from alembic.migration import MigrationContext
        from sqlalchemy import text, inspect as sa_inspect

        inspector = sa_inspect(connection)
        table_names = inspector.get_table_names()

        if "alembic_version" not in table_names:
            # Fresh DB created by create_all() — stamp to head
            connection.execute(
                text(
                    "CREATE TABLE IF NOT EXISTS alembic_version (version_num VARCHAR(32) NOT NULL)"
                )
            )
            connection.execute(
                text("INSERT INTO alembic_version (version_num) VALUES (:rev)"),
                {"rev": head_rev},
            )
            logger.info(f"Fresh database stamped to Alembic revision {head_rev}")
            return

        ctx = MigrationContext.configure(connection)
        current_rev = ctx.get_current_revision()

        if current_rev != head_rev:
            raise RuntimeError(
                f"Database schema is at revision {current_rev!r} but code expects "
                f"{head_rev!r}. Run `hokora db upgrade` to apply pending migrations."
            )

    async with engine.connect() as conn:
        await conn.run_sync(_check_revision)
        await conn.commit()
