# SPDX-FileCopyrightText: 2026 4ntenna <4ntenn@proton.me>, The Hokora Project
# SPDX-License-Identifier: AGPL-3.0-only
"""Alembic environment configuration for Hokora.

Supports both plain SQLite and SQLCipher-encrypted databases.
"""

import asyncio
import re
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import create_async_engine

from hokora.db.models import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def _get_url_and_key():
    """Get database URL and optional SQLCipher key from hokora config."""
    try:
        from hokora.config import load_config

        hokora_config = load_config()
        url = f"sqlite+aiosqlite:///{hokora_config.db_path}"
        # Route through the resolver chokepoint so alembic honours
        # db_keyfile (preferred) and inline db_key (deprecated).
        # Reading hokora_config.db_key directly would skip keyfile
        # support.
        db_key = hokora_config.resolve_db_key()
        return url, db_key
    except Exception:
        url = config.get_main_option("sqlalchemy.url")
        return url, None


def run_migrations_offline():
    """Run migrations in 'offline' mode — emit SQL to stdout."""
    url, _ = _get_url_and_key()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations():
    """Run migrations in 'online' mode with async engine.

    Use ``connectable.begin()`` (not ``connect()``) so DML emitted by a
    migration — including the ``UPDATE alembic_version`` — commits on
    block exit. Under SQLAlchemy 2.x, ``connect()`` never auto-commits
    DML; SQLite's implicit DDL-autocommit masks this for pure-DDL
    migrations (e.g. ``ADD COLUMN``), but any migration that emits an
    ``INSERT`` or ``UPDATE`` (table rebuilds, data backfills, the alembic
    version bump itself) will run without error and then silently roll
    back on close. ``begin()`` wraps the whole run in one transaction
    that commits on clean exit.
    """
    url, db_key = _get_url_and_key()

    if db_key:
        from hokora.db.engine import _patch_aiosqlite_for_sqlcipher

        _patch_aiosqlite_for_sqlcipher()

    connectable = create_async_engine(url, poolclass=pool.NullPool)

    async with connectable.begin() as connection:
        if db_key:
            if not re.match(r"^[0-9a-fA-F]{64}$", db_key):
                raise ValueError("db_key must be exactly 64 hex chars (generated by 'hokora init')")
            # SECURITY: db_key validated hex-only above; PRAGMA key does not support ? binding
            # Use hex literal format x'...' to match engine.py
            await connection.exec_driver_sql(f"PRAGMA key=\"x'{db_key}'\"")

        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online():
    """Run migrations in 'online' mode."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
